--DROP TABLE IF EXISTS users, locations, categories, events;

CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_uq UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,

    CONSTRAINT locations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,

    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_name_uq UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation        VARCHAR(2000)                           NOT NULL,
    category          BIGINT                                  NOT NULL,
    confirmedRequests INTEGER                                 NOT NULL,
    createdOn         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description       VARCHAR(7000)                           NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator         BIGINT                                  NOT NULL,
    location          BIGINT                                  NOT NULL,
    paid              BOOLEAN                                 NOT NULL,
    participantLimit  INTEGER                                 NOT NULL,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    requestModeration BOOLEAN                                 NOT NULL,
    state             VARCHAR(20)                             NOT NULL,
    title             VARCHAR(120)                            NOT NULL,
    views             INTEGER                                 NOT NULL,

    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_category_fk FOREIGN KEY (category) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT events_location_fk FOREIGN KEY (location) REFERENCES locations (id) ON DELETE CASCADE,
    CONSTRAINT events_initiator_fk FOREIGN KEY (initiator) REFERENCES users (id) ON DELETE CASCADE
);